
SELECT COUNTRY, TOTAL_DOSES_ADMINISTERED,
       DENSE_RANK() OVER (ORDER BY TOTAL_DOSES_ADMINISTERED DESC) as GLOBAL_RANK
FROM VACCINE_DATA;


SELECT COUNTRY, TOTAL_DOSES_ADMINISTERED,
       CASE 
            WHEN TOTAL_DOSES_ADMINISTERED > 1000000000 THEN 'SUSPICIOUS_HIGH_ENTRY'
            ELSE 'NORMAL'
       END as SECURITY_STATUS
FROM VACCINE_DATA;


SELECT SUBSTR(COUNTRY, 1, 3) || '***' as MASKED_COUNTRY, 
       TOTAL_DOSES_ADMINISTERED
FROM VACCINE_DATA;